@echo off
echo Installing dependencies...
call pnpm install
echo Generating database client...
call pnpm db:generate
echo Pushing schema to database...
call pnpm db:push
echo Starting dev server...
call pnpm dev
